image: ruby:2.7

cache:
  paths:
  - vendor/

before_script:
  - cd docs
  - gem install bundler
  - gem install bundler jekyll
  - bundle config set path 'vendor'
  - bundle install

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d ../public
  artifacts:
    paths:
    - public
  only:
  - master
