language: c

before_install:
      - sudo apt-get install libblas-dev liblapack-dev g++ gfortran libfftw3-dev tcsh

python:
      - "2.7"

install:
      - pip install numpy
      - pip install scipy
      - pip install matplotlib
      - pip install http://github.com/MMesch/SHTOOLS/zipball/develop
