language: c

matrix:
  include:
    # Test Python 2.7 and 3.6 on Linux and OSX
    - os: linux
      env: PYTHON_VERSION=2.7
    - os: linux
      env: PYTHON_VERSION=3.6

    - os: osx
      env: PYTHON_VERSION=2.7
    - os: osx
      env: PYTHON_VERSION=3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update;
       brew cask uninstall oclint;
       brew install fftw --with-fortran;
    else
       sudo apt-get update;
       sudo apt-get install libblas-dev liblapack-dev g++ gfortran tcsh;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
      export FFTW="/usr/local";
    else
      export OS="Linux";
    fi
  - if [[ "${PYTHON_VERSION:0:1}" == '2' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-${OS}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment
        python=$PYTHON_VERSION
        numpy
        scipy
        matplotlib
        jupyter
        mkl
  - conda install nbconvert
  - conda install -n test-environment -c eumetsat fftw3
  - source activate test-environment
  - pip install --no-deps .

script:
  - python examples/notebooks/test_notebooks.py
  - export MPLBACKEND=Agg
  - make -C examples/python -f Makefile no-timing
  - mkdir empty
  - cd empty
  - python -c "import pyshtools"

notifications:
    email: false
