channels:
    - conda-forge
dependencies:
    - fftw>=3.3.8
    - liblapack>=3.8
    - numpy
    - scipy>=0.14.0
    - matplotlib-base>=3.3
    - astropy>=4.0
    - xarray
    - requests
    - pooch>=1.1
    - tqdm
    - cartopy>=0.18.0
    - gmt>=6.1.1
    - pygmt>=0.2.0
    - palettable>=3.3
    - jupyter
    - pypandoc
    - flake8
    - pip
# Install ducc0 here, so we can run tests on the ducc0 backend
# NOTE: there is apparently a genuine conda-package for ducc0
# (see https://github.com/conda-forge/ducc0-feedstock), but this is not under
# my control and needs a few fixes, as far as I understand, so I'm installing
# from PyPI for now.
    - pip:
      - ducc0>=0.12
