name: pyshtools
channels:
    - conda-forge
dependencies:
    - python=3.8
    - fftw>=3.3.8
    - liblapack>=3.8
    - openblas
    - gmt>=6.1.1
    - numpy
    - scipy>=0.14.0
    - matplotlib>=3.3
    - astropy
    - xarray
    - requests
    - pooch
    - tqdm
    - cartopy>=0.18.0
    - pygmt>=0.2
    - palettable
    - jupyter
    - pypandoc
    - nb_conda_kernels