name: pyshtools
channels:
    - conda-forge
dependencies:
    - python>=3.5
    - numpy
    - scipy>=0.14.0
    - matplotlib
    - astropy
    - xarray
    - requests
    - pooch
    - tqdm
    - cartopy
    - pygmt
    - gmt
    - palettable
