name: pyshtools
channels:
    - conda-forge
dependencies:
    - python=3.7
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - jupyter
    - mkl
    - astropy
    - xarray
    - requests
    - cartopy
    - pygmt
    - gmt
    - pooch
    - tqdm
    - palettable
    - pip
