name: pyshtools
channels:
    - conda-forge
dependencies:
    - python>=3.6
    - numpy
    - scipy>=0.14.0
    - matplotlib>=3.3
    - astropy
    - xarray
    - requests
    - pooch
    - tqdm
    - cartopy
    - pygmt>=0.2
    - gmt>=6.1.1
    - palettable
    - jupyter
    - pypandoc