name = "SHTOOLS"
version = "4.7"
license = "BSD-3-Clause"
author = "Mar A. Wieczorek"
maintainer = "mark.a.wieczorek@gmail.com"
copyright = "2020 SHTOOLS"

[library]
source-dir="src"
build-script = "make all F95=$FC"
