name: pyshtools
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - fftw>=3.3.8
    - liblapack>=3.8
    - openblas
    - gmt>=6.1.1
    - pyshtools>=4.7
    - numpy
    - scipy>=0.14.0
    - matplotlib=3.3.*
    - astropy
    - xarray
    - requests
    - cartopy
    - pygmt>=0.2
    - pooch
    - tqdm
    - jupyter
    - palettable
    - pypandoc
