name: Continuous Integration Tests

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.10']

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true
        miniconda-version: "latest"
        activate-environment: ci_test
        environment-file: environment.yml

    - name: Set up Conda environment
      shell: bash -l {0}
      run: |
        mamba list -n ci_test

    - name: Install gcc for macOS
      shell: bash -l {0}
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew reinstall gcc

    - name: Build using pip
      shell: bash -l {0}
      run: |
        mamba env list
        pip install --no-deps .

    - name: Run tests
      shell: bash -l {0}
      run: |
        mamba env list
        python examples/notebooks/test_notebooks.py
        export MPLBACKEND=Agg
        make -C examples/python -f Makefile no-timing
        mkdir empty && cd empty
        python -c "import pyshtools"
