name: Continuous Integration Tests

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v1
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        auto-update-conda: true
        miniconda-version: "latest"
        activate-environment: ci_test

    - name: Set up Conda environment
      shell: bash -l {0}
      run: |
        conda init bash
        conda config --set always_yes yes --set changeps1 no
        conda install -n ci_test python=${{ matrix.python-version }}
        conda env update -n ci_test -f environment.yml
        conda list -n ci_test
        conda env list

    - name: Build using pip
      shell: bash -l {0}
      run: |
        conda env list
        conda activate ci_test
        pip3 install --no-deps .

    - name: Run tests
      # shell: bash -l {0}
      run: |
        conda env list
        python examples/notebooks/test_notebooks.py
        export MPLBACKEND=Agg
        make -C examples/python -f Makefile no-timing
        mkdir empty && cd empty
        python -c "import pyshtools"
